### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by eirikb** [eirikb/weecloud#11]
The current version can be run locally without any problems, but it is not aimed at one single user, and
it is not locked down. Would simply be like running weecloud.jit.su just from another computer.  
Should support:
- 1 global password, then autoconnect to defined (configured) host, port and weechat password.
- Defined (configured) host, can set port and pass. This allows running on multi-user systems. weechat password will suffice
- WeeCloud version, totally open. Users set host, port and password

**Comment by dennisse** [comment]
Why close this? This would be quite practical for a lot of users.

**Comment by eirikb** [comment]
Set in packages.config like this:

``` JSON
"options": {
  "host": "localhost",
  "port": 9001,
  "ssl": true
}
```
