### ISSUE TITLE
Connect to server,join rooms and dcc stat

### ISSUE THREAD

**Issue by benticlaskaris** [eirikb/weecloud#15]
It's not possible from the web interface to issue connect join commands and to get dcc stat like xfer.list

**Comment by eirikb** [comment]
You mean you are missing the windows?  
Every command should work as expected, such as `/connect`, although it can be difficult to use because the "status" windows are currently not being displayed.

**Comment by benticlaskaris** [comment]
i've tried but with no response to issue /connect and /join commands...

Am I missing something?

**Comment by benticlaskaris** [comment]
Ok now I've cornered the issue...

If the weechat istance isn't connected to any server, It's not possible to issue any command in the chat bar.

Also when connected to one server,typing /connect nameOfServer issues the command but the interface doesn't refresh so I'm forced to refresh the page to view the connected server.

Doing the same commands with qtweechat works and we have also the status window... 

I've forked the project to add the status window with dcc transfers

**Comment by eirikb** [comment]
The best way to handle this is most likely to just include all types of buffers, please see cee7af4f91724851c2dd9f4c212a26b4fc143839

**Comment by eirikb** [comment]
I'm closing this now as the commit I previously mentioned is deployed to weecloud.jit.su.  
It does make the menu much larger and more messy, but that is a another thing I'm working on.
