### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by ioga** [eirikb/weecloud#16]
Hi, can you please specify the license of this project?

Thanks in advance.

**Comment by eirikb** [comment]
Sure.

I guess I could just add same license as on https://github.com/eirikb/weechat.js ?  
I ask because I don't know if any of the libraries might prevent me from doing this.

**Comment by ioga** [comment]
Yeah, I think MIT license will work.

I guess all libraries in the project have some standard free software licenses, so there shouldn't be any restrictions.

Thanks.

**Comment by vivien** [comment]
In that case I would have suggested a free license such as the one WeeChat is released under, i.e. GPLv3 :)

**Comment by eirikb** [comment]
IANAL, but would it matter?  
(And yes I have seen http://stackoverflow.com/a/5610965)

**Comment by ioga** [comment]
@vivien WeeCloud is not derived work of WeeChat, so I think WeeChat's GPL won't make any restrictions on WeeCloud here.

**Comment by vivien** [comment]
@ioga You're right, but I was just suggesting WeeChat's license as a good choice.
@eirikb Not really atm, but my point is that when applicable, it is better to choose a license which protects the software (GPL) instead of the user (MIT, BSD).
