### ISSUE TITLE
_nicklist

### ISSUE THREAD

**Issue by eirikb** [eirikb/weecloud#4]
_nicklist is frequently sent to clients, this is causing large amount of bytes going over the cable.  
Disabling nicklist sync might help

**Comment by totalizator** [comment]
Is it disabled by default? I can't get it to show up (nicklist).

**Comment by eirikb** [comment]
It's actually not implemented yet. This issue is actually related to fetching the nicks using the protocol, just to get them into weecloud server

**Comment by totalizator** [comment]
This explains a lot. Thanks!

**Comment by eirikb** [comment]
Closing this for now. There is a nicklist now, although __nicklist_diff_ is not used. I see no reason to implement this now when we still need to support older versions of WeeChat that does not have it.
