### ISSUE TITLE
Mobile navigation

### ISSUE THREAD

**Issue by eirikb** [eirikb/weecloud#6]
Need a new and fancy way to navigate when using mobile. Tabs does not work very well on small screens

**Comment by dennisse** [comment]
I believe [this commit](https://github.com/eirikb/weecloud/commit/14d5f578a7b1043d5f3974a6dc3f6fd4ad45df8b), and [bufferlist.js](https://github.com/eirikb/weecloud/blob/master/public/js/bufferlist.js) somewhat fixes this issue?
The dropdown menu is a bit tricky to navigate if you have a lot of buffers, but it's OK.

**Comment by eirikb** [comment]
It's still kind of horrible. But I wonder if we just add notifications on the options then it will suddenly become much more usable

**Comment by eirikb** [comment]
Showing updates for now. Not the best solution but it works
